# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

resources:
  repositories:
  - repository: Sistema Taskit
    type: git
    name: Projeto-Integracao-Cypress/Sistema Taskit
    ref: main
    trigger:
    - main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Instalar dependencias'

- script: |
    npm test
  displayName: 'Executar testes'